### ISSUE TITLE
Mobile friendliness issues

### ISSUE THREAD

**Issue by jieshic** [autonlab/autonlab.github.io#16]
(Tested on iOS)
iPhone
1. Main page “Menu” fails to work
2. Image and text layout not optimized for vertical screen for main page and research areas page
3. Publications table cannot scroll to the right; fail to re-scale immediately when screen is rotated horizontally (it will re-scale if click on next page or reload the whole page)

iPad:
1. Menu is missing
2. Text alignment became "justify" type which paragraphs are stretched with equal line widths, as well as research areas page
3. Publication page has no table content
4. People page layout is not automatically adjusted, with all images squeezed on the same row.

**Comment by ngisolfi** [comment]
On mobile, the left/right placement of images/text leaves the images small and the text barely readable.  We should change this to top/bottom placement if the width of the browser is less than some threshold.

**Comment by ngisolfi** [comment]
changed a few things:

1. applications / research / impact are single column, making it easier to read on mobile
2. CMU logo replaced with vertical stack to provide more space for navbar and prevent spill on mobile
3. text alignment should scale better with variable browser width...i found a hack that seems to work, but there may be a more principled way to fix this

The issue with the publication table still exists.  If there are no other mobile friendly issues, I will reopen this in a new issue specific to the publication table.
