### ISSUE TITLE
mobile: whitespace when scrolling to right

### ISSUE THREAD

**Issue by betababb** [autonlab/autonlab.github.io#32]
while on iPhone13 Mini (and most likely other small screens) scrolling to the right is possible to the point where whitespace covers the entire screen on all main pages (have not checked any sub-pages, just those from the navbar)

**Comment by betababb** [comment]
might be a good place to start? https://www.codegrepper.com/code-examples/css/disable+horizontal+scroll+css+mobile

**Comment by betababb** [comment]
I believe I found a fix, but I have only tested this in Firefox DevTools, so I'm not sure yet how it would translate to the Jekyll format, but I believe this code (css) would need to be added to the layout.css page(s).

I just added "width: 100%;" and "overflow-x: hidden;" to the body and html elements (see attached pics for both), and it seems to be working.

This could also be accomplished by combining the two if that is easier like:

html, body {
  width: 100%;
  overflow-x: hidden;
}

adding the !important tag may be necessary though, however I did not need to when messing with it on DevTools. If so, it would look like this:

html, body {
  width: 100% !important;
  overflow-x: hidden !important;
}

![body](https://user-images.githubusercontent.com/110262149/186018111-fdb73910-b83c-4024-ad99-99d3e86a248f.png)
![html](https://user-images.githubusercontent.com/110262149/186018113-c656ca3a-1798-417a-b337-1c627c0b8f80.png)

**Comment by ngisolfi** [comment]
This fix works, thank you!!  I'll help set up your environment and walk you through the process so you can commit this change yourself.

**Comment by betababb** [comment]
Awesome, glad to hear it works! That would be great, looking forward to it!!

**Comment by betababb** [comment]
added code to page.css

Addressed in commit be18f2e
